# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2705eed9ddc6e9ec6f471ac017828573b251c72a5d26bb5156576883c6f5c58a84e3bf81b0a012d148c581f61fb747c3317dc17612af7bf3236656fcf517e83

test:
  secret_key_base: 5f410daab36ea0322fefb0565e85e4dec049460292a0c32c14dd72411d3e93e8cdf662a11141a52710eff7d5e700d3560f770c857a46510294f7e439ff315a80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
